services:
  mongodb:
    image: mongo:7
    container_name: nammongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    image: product-api:1.0
    container_name: product-api
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/productdb?authSource=admin

volumes:
  mongo_data: